name: animation_builder
description: Fluent and type-safe API to build keyframes and timing for Web Animation API
version: 0.1.0
homepage: https://github.com/tejainece/animation_builder

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.15.7
